-- MySQL Script generated by MySQL Workbench
-- 08/05/16 14:58:25
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Locadora
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Locadora` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `Locadora` ;

-- -----------------------------------------------------
-- Table `Locadora`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Locadora`.`Endereco` (
  `cep` VARCHAR(8) NOT NULL,
  `rua` VARCHAR(80) NULL,
  `bairro` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `numero` SMALLINT NOT NULL,
  PRIMARY KEY (`cep`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Locadora`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Locadora`.`Cliente` (
  `idCliente` INT NOT NULL,
  `pNome` VARCHAR(30) NOT NULL,
  `sNome` VARCHAR(50) NULL DEFAULT NULL,
  `telefone1` VARCHAR(11) NOT NULL,
  `telefone2` VARCHAR(11) NULL DEFAULT NULL,
  `cep` VARCHAR(8) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`idCliente`, `cep`),
  UNIQUE INDEX `idCliente_UNIQUE` (`idCliente` ASC),
  INDEX `cep_idx` (`cep` ASC),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC),
  CONSTRAINT `cep`
    FOREIGN KEY (`cep`)
    REFERENCES `Locadora`.`Endereco` (`cep`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Locadora`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Locadora`.`Categoria` (
  `idCategoria` INT NOT NULL,
  `nomeCategoria` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Locadora`.`Filme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Locadora`.`Filme` (
  `idFilme` INT NOT NULL,
  `tituloFilme` VARCHAR(50) NOT NULL,
  `anoLancamento` DATETIME NOT NULL,
  `idcategoria` INT NOT NULL,
  PRIMARY KEY (`idFilme`, `idcategoria`),
  INDEX `CategoID_idx` (`idcategoria` ASC),
  CONSTRAINT `CategoID`
    FOREIGN KEY (`idcategoria`)
    REFERENCES `Locadora`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Locadora`.`CategoriaShow`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Locadora`.`CategoriaShow` (
  `idCategoriaShow` INT NOT NULL,
  `nomeCategShow` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idCategoriaShow`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Locadora`.`Show`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Locadora`.`Show` (
  `idShow` INT NOT NULL,
  `tituloShow` VARCHAR(45) NOT NULL,
  `idCategoriaShow` INT NOT NULL,
  PRIMARY KEY (`idShow`, `idCategoriaShow`),
  INDEX `categorshow_idx` (`idCategoriaShow` ASC),
  CONSTRAINT `categorshow`
    FOREIGN KEY (`idCategoriaShow`)
    REFERENCES `Locadora`.`CategoriaShow` (`idCategoriaShow`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Locadora`.`DVD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Locadora`.`DVD` (
  `idDVD` INT NOT NULL,
  `codFilme` INT NOT NULL,
  `codShow` INT NULL,
  PRIMARY KEY (`idDVD`),
  INDEX `idFilme_DVD_idx` (`codFilme` ASC),
  INDEX `idShow_DVD_idx` (`codShow` ASC),
  CONSTRAINT `idFilme_DVD`
    FOREIGN KEY (`codFilme`)
    REFERENCES `Locadora`.`Filme` (`idFilme`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `idShow_DVD`
    FOREIGN KEY (`codShow`)
    REFERENCES `Locadora`.`Show` (`idShow`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Locadora`.`Blu-Ray`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Locadora`.`Blu-Ray` (
  `idBlu-Ray` INT NOT NULL,
  `codFilme` INT NOT NULL,
  `codShow` INT NULL,
  PRIMARY KEY (`idBlu-Ray`),
  INDEX `idFilme_Blue_idx` (`codFilme` ASC),
  INDEX `idShow_Blue_idx` (`codShow` ASC),
  CONSTRAINT `idFilme_Blue`
    FOREIGN KEY (`codFilme`)
    REFERENCES `Locadora`.`Filme` (`idFilme`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `idShow_Blue`
    FOREIGN KEY (`codShow`)
    REFERENCES `Locadora`.`Show` (`idShow`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Locadora`.`Locacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Locadora`.`Locacao` (
  `idLocacao` INT NOT NULL,
  `dtLocacao` DATETIME NOT NULL,
  `dtDevolucao` DATETIME NOT NULL,
  `idCliente` INT NOT NULL,
  `tipoDisco` INT NOT NULL,
  `status` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`idLocacao`),
  INDEX `idCliente_idx` (`idCliente` ASC),
  INDEX `tipoDisco_idx` (`tipoDisco` ASC),
  CONSTRAINT `idCliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `Locadora`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `tipoDisco_DVD`
    FOREIGN KEY (`tipoDisco`)
    REFERENCES `Locadora`.`DVD` (`idDVD`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `tipoDisco_Blu`
    FOREIGN KEY (`tipoDisco`)
    REFERENCES `Locadora`.`Blu-Ray` (`idBlu-Ray`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Locadora`.`Ator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Locadora`.`Ator` (
  `idAtor` INT NOT NULL,
  `nomeAtor` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idAtor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Locadora`.`Filme_tem_Ator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Locadora`.`Filme_tem_Ator` (
  `Filme_idFilme` INT NOT NULL,
  `Ator_idAtor` INT NOT NULL,
  PRIMARY KEY (`Filme_idFilme`, `Ator_idAtor`),
  INDEX `fk_Filme_has_Ator_Ator1_idx` (`Ator_idAtor` ASC),
  INDEX `fk_Filme_has_Ator_Filme1_idx` (`Filme_idFilme` ASC),
  CONSTRAINT `fk_Filme_has_Ator_Filme1`
    FOREIGN KEY (`Filme_idFilme`)
    REFERENCES `Locadora`.`Filme` (`idFilme`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Filme_has_Ator_Ator1`
    FOREIGN KEY (`Ator_idAtor`)
    REFERENCES `Locadora`.`Ator` (`idAtor`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Locadora`.`Cantor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Locadora`.`Cantor` (
  `idCantor` INT NOT NULL,
  `nomeCantor` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idCantor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Locadora`.`Show_tem_Cantor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Locadora`.`Show_tem_Cantor` (
  `Show_idShow` INT NOT NULL,
  `Cantor_idCantor` INT NOT NULL,
  PRIMARY KEY (`Show_idShow`, `Cantor_idCantor`),
  INDEX `fk_Show_has_Cantor_Cantor1_idx` (`Cantor_idCantor` ASC),
  INDEX `fk_Show_has_Cantor_Show1_idx` (`Show_idShow` ASC),
  CONSTRAINT `fk_Show_has_Cantor_Show1`
    FOREIGN KEY (`Show_idShow`)
    REFERENCES `Locadora`.`Show` (`idShow`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Show_has_Cantor_Cantor1`
    FOREIGN KEY (`Cantor_idCantor`)
    REFERENCES `Locadora`.`Cantor` (`idCantor`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
